name: "Build eSirOpenWrt Installer ISO"

on:
 workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 

      - name: "Checking out git repository"
        uses: actions/checkout@v2
      
      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/esir.sh
          chmod +x ${{ github.workspace }}/supportFiles/esirplayground/build.sh

      - name: "Build Image"
        run: |
          ./esir.sh
      
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "eSirOpenWrt-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/supportFiles/esirplayground/info.md
          files: |
            output/esiropenwrt-installer-x86_64.iso
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
